version: '2.1'
orbs:
  python: circleci/python@1.0.0
jobs:
  check:
    docker:
      - image: python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run : python sample.py
workflows:
  main:
    jobs:
      - check
